/* eslint-disable no-undef */
import './globals.css'
import type { Metadata } from 'next'
import { Lexend } from 'next/font/google'
import { ThemeProvider } from '@/components/theme-provider'
import NavBar from './components/NavBar'
import { ModeToggle } from '@/components/ModeToggle'

const lexe = Lexend({
  subsets: ['latin'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'GameBoost',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' style={lexe.style}>
      <body>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <div className='h-screen w-full flex'>
            <NavBar />
            <div className='w-full flex flex-col'>
              <header className='w-full flex items-center justify-end p-2'>
                <div className='flex flex-shrink-0 items-center space-x-2'>
                  <div className='flex flex-col items-end '>
                    <ModeToggle />
                  </div>
                </div>
              </header>
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
